apiVersion: v1
kind: Service
metadata:
  name: spring-swagger-service
spec:
  type: NodePort
  selector:
    app: spring-swagger-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
